### ISSUE TITLE
How properly instantiate a datepicker / jQuery at test level doesn't work ? 

### ISSUE THREAD

**Issue by yurikilian** [react-materialize/react-materialize#249]
Hi.

I successfully made  a DatePicker component using the available libraries from react-materialize.
However, I cannot use the component without declare materialize-css and jquery deps on index.html.

I used create-react-app facility.

Here is my code:

```
import React from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import idgen from 'react-materialize/lib/idgen';

export default class DatePicker extends React.Component {
    constructor(props) {
        super(props);
        this.renderFormat = 'dd !de mmmm !de yyyy';

        let defaultValue = this.props.defaultValue || '';
        this.state = { value: defaultValue,  renderedValue: defaultValue};
       
    }
    componentDidMount() {
        let diaSemana = [ 'Domingo', 'Segunda-Feira', 'Terca-Feira', 'Quarta-Feira', 'Quinta-Feira', 'Sexta-Feira', 'Sabado' ];
        let mesAno = [ 'Janeiro', 'Fevereiro', 'Marco', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro' , 'Dezembro' ];
        const component = this;

        window.$(this.refs.datepicker).pickadate({
            monthsFull: mesAno,
            weekdaysFull: diaSemana,
            monthsShort: [ 'Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez' ],
            weekdaysShort: [ 'Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab' ],
            weekdaysLetter: [ 'D', 'S', 'T', 'Q', 'Q', 'S', 'S' ],
            selectMonths: true,
            selectYears: true,
            hiddenName: true,
            format: this.renderFormat,
            today: "Hoje",
            close: "Fechar",
            clear: "Limpar",
            onStart:function(){
                if(component.state.value && component.state.value.isEmpty.length !== 0) {
                    this.set( 'select', component.state.value);
                }
            },
            onSet: function(e) {   
                component.onChange({target: {value: new Date(e.select), renderedValue: this.get(this.renderFormat)}});
                this.close();
            }, 
            onClose(e) {
                window.$(document.activeElement).blur();
            }
        });
    }

    renderIcon() {
        const {children} = this.props;
        let icon = null;
        if (React.Children.count(children) === 1) {
            icon = React
                .Children
                .only(children);
        }
        return icon === null
            ? null
            : React.cloneElement(icon, {className: 'prefix'});
    }

    renderLabelIfExists(id) {
        if (this.props.label) {
            return <label htmlFor={id}>{this.props.label}</label>
        }
    }

    appendSizeClassNames(classNames) {
         if(this.props.s) {
            classNames.push(['s' + this.props.s]);
        } 

        if(this.props.l) {
            classNames.push(['l' + this.props.l]);
        } 

        if(this.props.m) {
            classNames.push(['m' + this.props.m]);
        } 
    }

    triggerComponentOnChange(event) {
        delete event.target.renderedValue;
        event.target.name = this.props.name;
        this.props.onChange(event);
    }

    onChange(event) {
         this.setState({value: event.target.value, renderedValue: event.target.renderedValue});
         this.triggerComponentOnChange(event);    
    }

    render() {       
        let classNames = ['col', 'input-field'];
        this.appendSizeClassNames(classNames);

        const _id = 'datepicker-' + idgen();

        return (
            <div className={cx(classNames)}>
                {this.renderIcon()}
                <input type="text" id={_id} ref="datepicker" value={this.state.renderedValue} onChange={(event) => this.onChange(event)}/> 
                {this.renderLabelIfExists(_id)}
            </div>
        )
    }
}

DatePicker.propTypes = {
    s: PropTypes.number,
    m: PropTypes.number,
    l: PropTypes.number,
    className: PropTypes.string,
    label: PropTypes.node,
    error: PropTypes.string,
    success: PropTypes.string,
    defaultValue: PropTypes.instanceOf(Date),
    placeholder: PropTypes.string,
    id: PropTypes.string,
    icon: PropTypes.string,
    name: PropTypes.string,
    validate: PropTypes.bool,
    multiple: PropTypes.bool,
    browserDefault: PropTypes.bool,
    onLabel: PropTypes.string,
    offLabel: PropTypes.string,
    onChange: PropTypes.func
};

```

When I make an test with full Rendering throws me the error bellow:

```
TypeError: window.$ is not a function
      
      at DatePicker.componentDidMount (src/common/datepicker/DatePicker.js:20:16)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:76:22)
      at ReactReconcileTransaction.close (node_modules/react-dom/lib/ReactReconcileTransaction.js:80:26)
      at ReactReconcileTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:206:25)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:320:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.renderIntoDocument (node_modules/react-dom/lib/ReactTestUtils.js:91:21)
      at renderWithOptions (node_modules/enzyme/build/react-compat.js:209:26)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:94:59)
      at mount (node_modules/enzyme/build/mount.js:19:10)
      at Object.it (src/common/datepicker/DatePicker.test.js:10:65)
      at process._tickCallback (internal/process/next_tick.js:109:7)

```

Here is my test:
```

import React from 'react';
import { mount } from 'enzyme';

import DatePicker from './DatePicker';

describe('Giving a <DatePicker /> component ... ', () => {
  
  it('should render an input with text type when co', () => {
    const wrapper = mount(<DatePicker />);
    const h3 = <h3>Teste</h3>;

    expect(wrapper.contains(h3)).toEqual(true);
  });

});
```

Can someone help me to achieve component isolation of jquery and pickadate libs?

**Comment by yurikilian** [comment]
ps: i user webpack provide plugin but get no succcess in use $ at global context. Can someone tell me how  to achieve this without declare jquery dep on index.html?

**Comment by alextrastero** [comment]
This project doesn't work without jQuery, is there a specific reason why you don't want to add the jquery dependency in index.html ?

**Comment by yurikilian** [comment]
Hi @alextrastero  tks for reply. I'm using enzyme and the mount function to do a full render test.
I'm trying not to remove jquery, but put the lib in a global context that I can test my components in isolation.

In the test bellow, when a run it I get `TypeError: window.$ is not a function` because the jquery lib is at index.html, not in component itself.

```
import React from 'react';
import { mount } from 'enzyme';

import DatePicker from './DatePicker';

describe('Giving a <DatePicker /> component ... ', () => {
  it('should render an input with text type when co', () => {
    const wrapper = mount(<DatePicker />);
    const h3 = <h3>Teste</h3>;

    expect(wrapper.contains(h3)).toEqual(true);
  });

});
```
The code of <DatePicker /> compent is above, I'm using window.$(ref).datepicker(..) to instantiate a datepicker and I want test it wihout shallow.

**Comment by alextrastero** [comment]
ok, you can mock the Datepicker call method and simulate a click on check that Datepicker has been called.

Add the global method here: https://github.com/react-materialize/react-materialize/blob/master/test/helper.js

And check how it was done here: https://github.com/react-materialize/react-materialize/blob/master/test/SideNavSpec.js#L68

Good luck!

**Comment by alextrastero** [comment]
Please try `react-materialize3.x` and reopen if this is still happening, thanks!
