### ISSUE TITLE
🚨 Jest React-Materialize - TypeError: $(...).collapsible is not a function

### ISSUE THREAD

**Issue by VGamezz19** [react-materialize/react-materialize#505]
### Description

Problem when try to run my unit test in Jest.

### Steps to Reproduce

1. follow this case https://stackoverflow.com/questions/41844947/reactjs-jest-jquery-is-not-defined
2. yarn test
3. Error

```sh
   console.error node_modules/react-dom/cjs/react-dom.development.js:9747
      The above error occurred in the <Collapsible> component:
          in Collapsible (at Folder.js:54)
          in Folder (at Sidenav.js:99)
          in section (at Sidenav.js:58)
          in div (created by Paper)
          in Paper (created by Drawer)
          in div (created by Drawer)
          in Drawer (at Sidenav.js:52)
          in MuiThemeProvider (at Sidenav.js:51)
          in div (at Sidenav.js:49)
          in Sidenav (at App.js:121)
          in article (at App.js:120)
          in section (at App.js:119)
          in App (created by Route)
          in Route (at RoutingApp.js:10)
          in Switch (at RoutingApp.js:7)
          in Router (created by BrowserRouter)
          in BrowserRouter (at RoutingApp.js:5)
          in Routing (at App.test.js:7)
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● renders without crashing

    TypeError: $(...).collapsible is not a function
      
      at Collapsible.componentDidMount (node_modules/react-materialize/lib/Collapsible.js:53:28)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:8770:24)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:9946:9)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:542:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:126:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:36:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:581:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:438:27)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:10050:9)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:11017:42)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:10967:7)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:10878:7)
      at scheduleWorkImpl (node_modules/react-dom/cjs/react-dom.development.js:10732:11)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:10689:12)
      at scheduleTopLevelUpdate (node_modules/react-dom/cjs/react-dom.development.js:11193:5)
      at Object.updateContainer (node_modules/react-dom/cjs/react-dom.development.js:11231:7)
      at node_modules/react-dom/cjs/react-dom.development.js:15226:19
      at Object.unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:11102:12)
      at renderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:15225:17)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:15290:12)
      at Object.<anonymous>.it (tests/App.test.js:7:22)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)
```

this is the important message

>
>TypeError: $(...).collapsible is not a function
>

I think that I need import materialize.js in JEST  in some way, but I do not know how

### Versions

"react-materialize": "^2.1.0",
"materialize-css": "^0.100.2",
"react": "^16.2.0",

**Comment by VGamezz19** [comment]
## More Info:

i'm using `create-react-app` and i use this configuration to run my Jest

```js
// ./config/polyfills.js

import $ from 'jquery';
global.$ = global.jQuery = $;

if (typeof Promise === 'undefined') {
  // Rejection tracking prevents a common issue where React gets into an
  // inconsistent state due to an error, but it gets swallowed by a Promise,
  // and the user has no idea what causes React's erratic future behavior.
  require('promise/lib/rejection-tracking').enable();
  window.Promise = require('promise/lib/es6-extensions.js');
}

// fetch() polyfill for making API calls.
require('whatwg-fetch');

// Object.assign() is commonly used with React.
// It will use the native implementation if it's present and isn't buggy.
Object.assign = require('object-assign');

// In tests, polyfill requestAnimationFrame since jsdom doesn't provide it yet.
// We don't polyfill it in the browser--this is user's responsibility.
if (process.env.NODE_ENV === 'test') {
  require('raf').polyfill(global);
}

**Comment by VGamezz19** [comment]
## ⚠️ ⭐️ Resolved

install
`yarn add jquery hammerjs materialize-css`
in the configuration file for Jest, put this

```js
require ('jquery');
require ('hammerjs')
require ('materialize-css')
```
and works!

**Comment by alextrastero** [comment]
Hey @VGamezz19, thanks for sharing your findings. This will probably help other users down the road 👍
